project_id = "yaincoxihiqdksxgrsrk"

[functions.ai-chat]
verify_jwt = true

[functions.calculate-who5-card]
verify_jwt = true

[functions.nyvee-assess]
verify_jwt = true

[functions.music-therapy-start]
verify_jwt = true

[functions.music-therapy-submit]
verify_jwt = true

[functions.emotional-scan]
verify_jwt = true

[functions.story-music-generate]
verify_jwt = true

[functions.coach-ai-assist]
verify_jwt = true
