project_id = "yaincoxihiqdksxgrsrk"

[functions.ai-chat]
verify_jwt = true

[functions.assess-start]
verify_jwt = true

[functions.assess-submit]
verify_jwt = true

[functions.assess-aggregate]
verify_jwt = true

[functions.calculate-who5-card]
verify_jwt = true

[functions.nyvee-assess]
verify_jwt = true

[functions.music-therapy-start]
verify_jwt = true

[functions.music-therapy-submit]
verify_jwt = true

[functions.emotional-scan]
verify_jwt = true

[functions.story-music-generate]
verify_jwt = true

[functions.coach-ai-assist]
verify_jwt = true

[functions.coach-assess-start]
verify_jwt = true

[functions.coach-assess-submit]
verify_jwt = true

[functions.team-aggregate-b2b]
verify_jwt = true

[functions.send-invitation-email]
verify_jwt = true

[functions.generate-pdf-report]
verify_jwt = true

[functions.team-notifications]
verify_jwt = true

[functions.delete-user-data]
verify_jwt = true

[functions.hume-emotion-detect]
verify_jwt = true

[functions.suno-music-generate]
verify_jwt = true
